name = "SumSpace"
uuid = "df26dd89-bd05-444b-823e-d0e60161d2dd"
authors = ["john.papad "]
version = "0.1.0"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ClassicalOrthogonalPolynomials = "0.5.1"
julia = "1.6"